### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by fathomssen** [ANovitsky/redmine_shared_api#1]
Hi

It would be great to have filters for the shared API. E.g. use "shared/custom_fields.json?customized_type=time_entry" to get all custom fields for time entries.

Best regards
Frederick Thomssen

**Comment by ANovitsky** [comment]
But you can filter it in your code, usually custom_fields is not a big data.

**Comment by fathomssen** [comment]
To be honest, I don't remember anymore why I thought such a filter would be necessary. So I will close this issue.

Thanks for your reply, anyway!
